// Server actions return codes, never prose — the UI is bilingual, so the
// wording has to be chosen on the client where the dictionary lives.
export type ErrorCode =
  | "invalid_name"
  | "invalid_phone"
  | "short_password"
  | "taken"
  | "create_failed"
  | "network"
  | "pick_failed"
  | "clear_failed"
  | "duplicate_dish"
  | "dish_name_too_short"
  | "session_expired"
  | "reset_refused"
  | "reset_expired"
  | "reset_locked"
  | "reset_failed"
  | "self_deactivate"
  | "self_delete"
  | "delete_failed"
  | "owes_money"
  | "guest_add_failed"
  | "guest_remove_failed"
  | "event_failed"
  | "invalid_title"
  | "invalid_date"
  | "invalid_total"
  | "pay_failed"
  | "amount_too_big"
  | "invalid_amount"
  | "no_admin"
  | "generic";

export type ActionResult = { error?: ErrorCode; orphaned?: number };
